COUNTDOWN_INITIAL_SYSTEM = (
    "You are a careful and precise solver for arithmetic countdown puzzles.\n"
    "You must strictly follow the rules and output the final arithmetic expression "
    "in the required format."
)

COUNTDOWN_INITIAL_USER_TEMPLATE = (
    "You are given the following numbers and a target:\n"
    "Numbers: {numbers}\n"
    "Target: {target}\n\n"
    "Goal:\n"
    "Construct a single arithmetic expression that uses only the given numbers, each at most once,\n"
    "and evaluates exactly to the target {target}.\n\n"
    "Rules for the expression:\n"
    "- Use only the numbers {numbers}, each at most once.\n"
    "- The expression must evaluate exactly to {target}.\n"
    "- Do NOT include the target number {target} itself anywhere in the expression.\n"
    "- Use ONLY the characters: digits, '+', '-', '*', '/', '(', ')'.\n"
    "- Do NOT include an '=' sign.\n\n"
    "Example (format illustration):\n"
    "Numbers: [2, 3, 4, 6]\n"
    "Target: 24\n"
    "A valid final expression could be:\n"
    "  \\boxed{{6*4}}\n"
    "This uses only the given numbers (2, 3, 4, 6) at most once each, does not write 24 anywhere,\n"
    "and the expression 6*4 evaluates to 24.\n\n"
    "Output instructions:\n"
    "- You may include brief reasoning if you wish.\n"
    "- On the LAST line, write ONLY the final expression in the form:\n"
    "  \\boxed{{<expression>}}\n"
    "- Inside \\boxed{{}} you must put ONLY the arithmetic expression, with no extra text.\n"
    "- If you do not follow this format exactly, the answer will be marked incorrect.\n"
)

COUNTDOWN_REPAIR_SYSTEM = (
    "You are a math solver specialized in arithmetic countdown puzzles.\n"
    "You will receive the puzzle specification, a previous attempt, and binary feedback "
    "indicating whether the previous answer was correct or incorrect.\n"
    "Use this information to produce a better, corrected solution in the required format."
)

COUNTDOWN_REPAIR_USER_TEMPLATE = (
    "Puzzle specification:\n"
    "Numbers: {numbers}\n"
    "Target: {target}\n\n"
    "Previous attempt:\n"
    "{previous_answer}\n\n"
    "Verifiable feedback:\n"
    "{feedback}\n\n"
    "Your task:\n"
    "Produce a NEW arithmetic expression that satisfies all of the following:\n"
    "- Uses only the numbers {numbers}, each at most once.\n"
    "- Evaluates exactly to {target}.\n"
    "- Does NOT include the target number {target} itself anywhere in the expression.\n"
    "- Use ONLY the characters: digits, '+', '-', '*', '/', '(', ')'.\n"
    "- Do NOT include an '=' sign.\n"
    "- Do NOT simply repeat the previous incorrect attempt.\n\n"
    "Example (format illustration):\n"
    "Numbers: [2, 3, 4, 6]\n"
    "Target: 24\n"
    "Previous attempt:\n"
    "  \\boxed{{2*3*4}}\n"
    "Verifiable feedback:\n"
    "  incorrect\n"
    "A valid corrected answer could be:\n"
    "  \\boxed{{6*4}}\n"
    "Here the new expression is different from the previous attempt, uses only allowed numbers,\n"
    "does not write 24 explicitly, and evaluates to the correct target 24.\n\n"
    "Output instructions:\n"
    "- You may include a short explanation if you wish.\n"
    "- On the LAST line, write ONLY the final expression in the form:\n"
    "  \\boxed{{<expression>}}\n"
    "- Inside \\boxed{{}} you must put ONLY the arithmetic expression, with no extra text.\n"
    "- If you do not follow this format exactly, the answer will be marked incorrect.\n"
)