MINI_SUDOKU_INITIAL_PROMPT = (
    "You are solving 4x4 Mini Sudoku puzzles.\n\n"
    "Rules:\n"
    "- Each row must contain the numbers 1, 2, 3, 4 exactly once.\n"
    "- Each column must contain the numbers 1, 2, 3, 4 exactly once.\n"
    "- Each 2x2 subgrid must contain the numbers 1, 2, 3, 4 exactly once.\n"
    "- The character '_' represents an empty cell that you must fill.\n\n"
    "Example:\n"
    "Puzzle:\n"
    "4 _ _ _\n"
    "_ 3 _ _\n"
    "_ 1 3 _\n"
    "_ _ _ _\n\n"
    "Correct solution (output format):\n"
    "```\n"
    "4 2 1 3\n"
    "1 3 4 2\n"
    "2 1 3 4\n"
    "3 4 2 1\n"
    "```\n\n"
    "Now solve the following 4x4 Mini Sudoku puzzle:\n\n"
    "Puzzle:\n"
    "{puzzle}\n\n"
    "Instructions for your answer:\n"
    "- Fill all '_' with digits from 1 to 4.\n"
    "- Respect all the Mini Sudoku rules above.\n"
    "- Your FINAL answer must be ONLY one Markdown code block containing exactly 4 lines.\n"
    "- Each line should have 4 numbers separated by single spaces.\n"
    "- Do NOT add explanations, comments, or any extra text outside the code block.\n\n"
    "Now output your final solution:\n"
)

MINI_SUDOKU_REPAIR_PROMPT = (
    "You are solving 4x4 Mini Sudoku puzzles and correcting a previous attempt.\n\n"
    "Rules:\n"
    "- Each row must contain the numbers 1, 2, 3, 4 exactly once.\n"
    "- Each column must contain the numbers 1, 2, 3, 4 exactly once.\n"
    "- Each 2x2 subgrid must contain the numbers 1, 2, 3, 4 exactly once.\n"
    "- The character '_' represents an empty cell in the original puzzle.\n"
    "- You may NOT change the originally given numbers in the puzzle.\n\n"
    "Example:\n"
    "Original puzzle:\n"
    "4 _ _ _\n"
    "_ 3 _ _\n"
    "_ 1 3 _\n"
    "_ _ _ _\n\n"
    "Correct solution (output format):\n"
    "```\n"
    "4 2 1 3\n"
    "1 3 4 2\n"
    "2 1 3 4\n"
    "3 4 2 1\n"
    "```\n\n"
    "Now consider the following Mini Sudoku instance.\n\n"
    "Original puzzle:\n"
    "{puzzle}\n\n"
    "Previous (incorrect or incomplete) attempt:\n"
    "```\n"
    "{previous_answer}\n"
    "```\n\n"
    "Your task:\n"
    "- Use the previous attempt as a starting point.\n"
    "- Detect and fix any Sudoku rule violations.\n"
    "- Make sure the final grid satisfies ALL Mini Sudoku rules.\n"
    "- You may keep any entries from the previous attempt that are consistent with the rules.\n"
    "- If the previous attempt is badly wrong, you may rewrite the whole grid.\n\n"
    "Output format:\n"
    "- Your FINAL answer must be ONLY one Markdown code block containing exactly 4 lines.\n"
    "- Each line should have 4 numbers separated by single spaces.\n"
    "- Do NOT add explanations, comments, or any extra text outside the code block.\n\n"
    "Now output your corrected final solution:\n"
)