NQUEENS_INITIAL_SYSTEM = (
    "You are a careful and precise solver for n-queens completion puzzles.\n"
    "You must strictly follow the rules and output the final completed board "
    "in the required format."
)

NQUEENS_INITIAL_USER_TEMPLATE = (
    "Your job is to complete an n x n chess board with n queens in total, such that no two attack each other.\n"
    "\n"
    "Board size: {n} x {n}\n"
    "Total queens required: {total_queens}\n"
    "Number of new queens you must place: {num_to_place}\n"
    "\n"
    "Current board:\n"
    "{board_text}\n"
    "\n"
    "Rules:\n"
    "- A queen attacks along its row, column, and both diagonals.\n"
    "- You may place a new queen by replacing an underscore (_) with a Q.\n"
    "- All existing queens (Q) on the board must remain where they are.\n"
    "- In the final board, there must be exactly one queen in each row and each column,\n"
    "  and no two queens may attack each other.\n"
    "\n"
    "Goal:\n"
    "- Place the remaining queens so that the final board satisfies all of the above rules.\n"
    "\n"
    "Example (for illustration only — do NOT copy this board):\n"
    "Input board:\n"
    "_ _ Q _\n"
    "_ _ _ _\n"
    "_ _ _ _\n"
    "_ _ _ _\n"
    "\n"
    "A valid completed board would be:\n"
    "_ _ Q _\n"
    "Q _ _ _\n"
    "_ _ _ Q\n"
    "_ Q _ _\n"
    "\n"
    "Output instructions:\n"
    "- You may include brief step-by-step reasoning if you wish.\n"
    "- At the VERY END of your answer, output ONLY the completed board inside a Markdown code block:\n"
    "  ```\n"
    "  <completed board here>\n"
    "  ```\n"
    "- Inside the code block:\n"
    "  * Each row must be on its own line.\n"
    "  * Entries in a row are separated by single spaces.\n"
    "  * Use ONLY the characters '_' and 'Q'.\n"
    "- Do NOT include any extra text, comments, or labels inside the code block.\n"
    "- Do NOT output any text after the final code block.\n"
)

NQUEENS_REPAIR_SYSTEM = (
    "You are a solver specialized in n-queens completion puzzles.\n"
    "You will receive the puzzle specification, a previous attempt, and binary feedback\n"
    "indicating whether the previous answer was correct or incorrect.\n"
    "Use this information to produce a better, corrected solution in the required format."
)

NQUEENS_REPAIR_USER_TEMPLATE = (
    "Puzzle specification:\n"
    "Board size: {n} x {n}\n"
    "Total queens required: {total_queens}\n"
    "Number of new queens to place: {num_to_place}\n"
    "\n"
    "Current board:\n"
    "{board_text}\n"
    "\n"
    "Previous attempt:\n"
    "{previous_answer}\n"
    "\n"
    "Verifiable feedback (correct/incorrect):\n"
    "{binary_feedback}\n"
    "\n"
    "Example (illustration of a repair task):\n"
    "Current board:\n"
    "_ _ Q _\n"
    "_ _ _ _\n"
    "_ _ _ _\n"
    "_ _ _ _\n"
    "\n"
    "Previous attempt:\n"
    "Q _ Q _\n"
    "_ _ _ _\n"
    "_ _ _ Q\n"
    "_ Q _ _\n"
    "\n"
    "Feedback: incorrect\n"
    "\n"
    "A valid corrected solution would instead keep the original queen fixed and place queens as:\n"
    "_ _ Q _\n"
    "Q _ _ _\n"
    "_ _ _ Q\n"
    "_ Q _ _\n"
    "\n"
    "Your task:\n"
    "- Produce a NEW completed board that satisfies all of the following:\n"
    "  * All existing queens on the original board remain in place.\n"
    "  * Exactly {total_queens} queens appear on the final board.\n"
    "  * No two queens attack each other (no shared row, column, or diagonal).\n"
    "  * The board is still {n} x {n}, filled only with '_' and 'Q'.\n"
    "- Do NOT simply repeat the previous incorrect attempt.\n"
    "\n"
    "Output instructions:\n"
    "- You may include a short explanation of why your new placement is valid.\n"
    "- At the VERY END of your answer, output ONLY the completed board inside a Markdown code block:\n"
    "  ```\n"
    "  <completed board here>\n"
    "  ```\n"
    "- Inside the code block:\n"
    "  * Each row must be on its own line.\n"
    "  * Entries in a row are separated by single spaces.\n"
    "  * Use ONLY the characters '_' and 'Q'.\n"
    "- Do NOT include any extra text, comments, or labels inside the code block.\n"
    "- Do NOT output any text after the final code block.\n"
)